### ISSUE TITLE
feature request: actionlintの導入

### ISSUE THREAD

**Issue by MH4GF** [route06/actions#4]
https://github.com/rhysd/actionlint

## やりたいこと

- actionlintを使うreusable workflowの追加
- このリポジトリのPR作成時にactionlintが実行されるように

**Comment by masutaka** [comment]
@MH4GF

個人リポジトリで導入したので、このリポジトリでも https://github.com/route06/actions/pull/35 で検証開始してみました。
コメント等あればよろしくお願いします！😄

> - actionlintを使うreusable workflowの追加

reusable workflow は要らない気がしました👀

**Comment by MH4GF** [comment]
@masutaka 調査ありがとうございますー！コメントしました！

> reusable workflow は要らない気がしました👀

ですねー、やるとしてもstarter workflowになりそうですよね。

---

このissueはどう進めるとよいでしょうね、actionlintの導入には既存コードの修正が必要ってことですよね 👀

**Comment by masutaka** [comment]
> このissueはどう進めるとよいでしょうね、

https://github.com/route06/actions/pull/35 で導入しつつ、既存コードを修正します。大事（おおごと）になりそうならまた考えます 💪😄

**Comment by MH4GF** [comment]
@masutaka 良さそうと思います！ADRはなくてもよいかな...?と思いましたが、判断お任せしますー！！

**Comment by masutaka** [comment]
> ADRはなくてもよいかな...?と思いましたが、判断お任せしますー！！

あざます！

[ls-lint で間接的に書いてました](https://github.com/route06/actions/blob/v2.1.3/docs/adr/003-%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%95%E3%83%AD%E3%83%BC%E3%81%AE%E5%91%BD%E5%90%8D%E8%A6%8F%E5%89%87.md)が、ファイル名を snake_case に決定したという ADR で利用者にアクションを促すものでしたね。

actionlint は導入以外に何かを変えたわけではないので、ADR は書かないことにしました。

**Comment by masutaka** [comment]
## まとめ

actionlint を CI として導入しました。

* https://github.com/route06/actions/pull/35

reusable workflow の提供は見送りました。https://github.com/route06/actions/issues/4#issuecomment-2172054208

---

関連してちょっとしたリファクタリング PR も作りました。こちらのマージを待つ必要はないため、クローズします。

* https://github.com/route06/actions/pull/38
