### ISSUE TITLE
バージョニングの方法を決める

### ISSUE THREAD

**Issue by MH4GF** [route06/actions#7]
## 概要

route06/actionsの利用者が、バージョンを指定して利用できるようにする。以下のようなイメージ:

- `uses: route06/actions/.github/workflows/_add-assignee-to-pr.yml@v1.0.0`
- `uses: route06/actions/.github/workflows/_add-assignee-to-pr.yml@v1` 
    - v1系の最新バージョンがpublishされたら自動で利用可能になる

**Comment by MH4GF** [comment]
## 前提情報

- `{owner}/{repo}/.github/workflows/{filename}@{ref}` のrefはタグやブランチ名やコミットハッシュが指定可能
    - [Reusing workflows - GitHub Docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow)
- `v1.0.0` はタグのプッシュで実現可能
    - ただ、提供するreusable workflowそれぞれにバージョンを設定する みたいなことはできない
- `v1.0.1` が追加されたら `v1` で追従する方法として、 `v1` はブランチ名として定義し、タグのpushで発火するworkflowでブランチに取り込む方法がある
    - ref: [GitHub Actionsでメインバージョンのブランチ維持](https://r7kamura.com/articles/2022-04-16-keep-main-version-branch)

**Comment by MH4GF** [comment]
意思決定なのでADRを書くか ✍🏻

**Comment by masutaka** [comment]
@MH4GF 

https://github.com/route06/actions/issues/7#issuecomment-1892051316

> - セマンティックバージョニングを採用する 例:
>     - 既存のworkflowの改善 ... patch
>     - 新しいworkflowの追加 ... minor
>     - 既存のworkflowの破壊的変更 ... major

私も同じことを思っていました。👍

> - `v1.0.0` のような参照方法を提供し、git tagで運用する

ですね。

>     - git tagの運用に https://github.com/Songmu/tagpr を採用する

最初は手作業で、面倒だったり余裕があれば採用すれば良いかなと思いました。

> - `v1` のような参照方法を提供し、git branchで運用する
>     - git tagのpushで発火しブランチで追従するワークフローを作成する

`v1.x.x` の先端を指し続ける `v1` のタグも提供する感じですかね？ 余裕があればやっても良いかな？

ちょっと調べましたが、`actions/checkout` は [.github/workflows/update-main-version.yml](https://github.com/actions/checkout/blob/v4.1.1/.github/workflows/update-main-version.yml) で `v1` 等を最新にし続けていました。`on: workflow_dispatch` なので、新しいバージョンをリリースしたら、手動でこの workflow を実行していると思います。

## 補足

GitHub Actions の `uses: actions/checkout@v4` 等で指定するタグはあくまで Git のタグです。この場合は actions/checkout が v4 の git tag を作成しており、常に v4 の最新を指すようにメンテナンスされているので、v4 が使えます。

https://github.com/actions/checkout/tags

<img width="473" alt="actions/checkout@v4 は v4.x.x の先端を指す" src="https://github.com/route06/actions/assets/170014/1829df23-139e-4d13-a811-e18c0575cd33">

**Comment by MH4GF** [comment]
@masutaka 確認ありがとうございます 😄 

> 最初は手作業で、面倒だったり余裕があれば採用すれば良いかなと思いました。

特に強い理由もないので、一旦そうしましょうか 👍🏻 

> v1.x.x の先端を指し続ける v1 のタグも提供する感じですかね？ 余裕があればやっても良いかな？

これがあった方がいいかなーと思っていた背景として、この後社内のリポジトリで一括で差し替える作業をする予定ですが、その後の保守が簡単になるので先んじて入れておきたいなという気持ちでした。

> ちょっと調べましたが、actions/checkout は [.github/workflows/update-main-version.yml](https://github.com/actions/checkout/blob/v4.1.1/.github/workflows/update-main-version.yml) で v1 等を最新にし続けていました。on: workflow_dispatch なので、新しいバージョンをリリースしたら、手動でこの workflow を実行していると思います。

なるほど 👀 actions/checkoutはtagのforce pushで運用しているんですね。確かにbranchじゃなくてこちらでもよさそう。

---

自分で保守しているカスタムアクションがあり、そこで最新バージョン追従の運用はしていたので、それを持ってこようと思っていました。
https://github.com/MH4GF/dependency-cruiser-report-action/blob/main/.github/workflows/keep-main-version-branch.yml

**Comment by masutaka** [comment]
> これがあった方がいいかなーと思っていた背景として、この後社内のリポジトリで一括で差し替える作業をする予定ですが、その後の保守が簡単になるので先んじて入れておきたいなという気持ちでした。

分かります。みんながみんな Dependabot を導入するわけではないですからね。😅

> 自分で保守しているカスタムアクションがあり、そこで最新バージョン追従の運用はしていたので、それを持ってこようと思っていました。

さすが！ 良いと思います！ 😁

* セマンティックバージョニングを採用する
* タグの更新は一旦手動。面倒だったり余裕があれば tagpr を採用する
* v1 等は v1.x.x の最新を指すようにする

**Comment by MH4GF** [comment]
@masutaka 確認・整理ありがとうございます 😄  後ほどADRに起こします。

**Comment by MH4GF** [comment]
TODO

- [ ] ADRのPR: https://github.com/route06/actions/pull/11 
- [ ] v1.0.0のタグを打つ
- [ ] v1のタグを打つ

**Comment by MH4GF** [comment]
素朴に手元からタグを打ち作成

```sh
$ git tag v1.0.0

$ git tag v1

$ git push --tag
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To ssh://github.com/route06/actions.git
 * [new tag]         v1 -> v1
 * [new tag]         v1.0.0 -> v1.0.0
```

- https://github.com/route06/actions/releases/tag/v1.0.0
- https://github.com/route06/actions/releases/tag/v1
